# Generated by Django 3.0 on 2021-07-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=800, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('sku', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XsollaAPI.Product')),
            ],
        ),
        migrations.CreateModel(
            name='UnitAtStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='XsollaAPI.StockUnit')),
            ],
        ),
    ]
